name: Build

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      BUILD_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Add ARM64 Repositories
        run: |
          codename=$(lsb_release -s -c)
          sudo dpkg --add-architecture arm64
          sudo add-apt-repository -yn "deb [arch=arm64] http://ports.ubuntu.com/ $codename main multiverse universe"
          sudo add-apt-repository -yn "deb [arch=arm64] http://ports.ubuntu.com/ $codename-security main multiverse universe"
          sudo add-apt-repository -yn "deb [arch=arm64] http://ports.ubuntu.com/ $codename-backports main multiverse universe"
          sudo add-apt-repository -yn "deb [arch=arm64] http://ports.ubuntu.com/ $codename-updates main multiverse universe"

      - name: Install GCC for ARM64
        run: |
          sudo apt-get install gcc-aarch64-linux-gnu

      - name: Install VLC
        run: |
          sudo apt-get update
          sudo apt-get install libvlc-dev libvlc-dev:arm64

      - name: Build for AMD64
        run: go build -o dist/${{ env.BUILD_NAME }}-amd64 -v

      - name: Build for ARM64
        env:
          CC: aarch64-linux-gnu-gcc
          GOARCH: arm64
          CGO_ENABLED: 1
        run: go build -o dist/${{ env.BUILD_NAME }}-arm64 -v

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}
          path: ./dist/*
