name: Build

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    env:
      BUILD_NAME: ${{ github.event.repository.name }}-${{ github.ref }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Install VLC
        run: |
          sudo apt-get update
          sudo apt-get -y install libvlc-dev vlc-plugin-base

      - name: Build
        env:
          GOARCH: ${{ matrix.arch }}
        run: go build -o dist/${{ env.BUILD_NAME }} -v ./...

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}
          path: ./dist/*
