#!/bin/bash

# Allow application to use port 80
setcap 'cap_net_bind_service=+ep' /usr/bin/openjukebox

# Restore state on whether the service was enabled/disabled
deb-systemd-helper --user unmask openjukebox.service

# Restart service
deb-systemd-invoke --user restart openjukebox.service

exit 0