#!/bin/bash

# Allow application to use port 80
setcap 'cap_net_bind_service=+ep' /usr/bin/openjukebox

# Restart service (only for users with service enabled)
deb-systemd-invoke --user restart openjukebox.service 2>/dev/null

exit 0